"""empty message

Revision ID: 8984dc9dffad
Revises: 3564e8e8aee8
Create Date: 2022-05-11 21:44:14.120375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8984dc9dffad'
down_revision = '3564e8e8aee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('post', sa.Integer(), nullable=True),
    sa.Column('writer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['writer'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('about', sa.Text(), nullable=False))
    op.add_column('posts', sa.Column('writer', sa.Integer(), nullable=True))
    op.alter_column('posts', 'category',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('posts', 'votes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'posts', 'users', ['writer'], ['id'])
    op.drop_column('posts', 'on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('on', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'votes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'category',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_column('posts', 'writer')
    op.drop_column('posts', 'about')
    op.drop_table('comment')
    # ### end Alembic commands ###
